# Cloudflare wrangler configuration file

name = "selfdiscovery"
compatibility_date = "2023-10-02"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Bind the D1 database
[[d1_databases]]
binding = "DB"
database_name = "selfdiscovery"
database_id = "7dcf2377-8198-4f7f-ba51-614134c8be98"

[site]
bucket = ".output/public"

[build]
command = "npm run build"