# Simple Cloudflare Pages configuration
name = "selfdiscovery"
compatibility_date = "2023-10-02"
pages_build_output_dir = ".output/public"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "selfdiscovery"
database_id = "7dcf2377-8198-4f7f-ba51-614134c8be98"